version: "2"

networks:

  back-tier:
    driver: bridge

services:

  logger:
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  base:
    extends: logger
    networks:
      - back-tier

  base_api:
    extends: base
    environment:
      PORT: 80
      NODE_ENV: development
      NODE_PATH: "/opt/app/lib"
    expose:
      - 80
    command: npm run start
    mem_limit: 512m

  base_postgres:
    extends: base
    mem_limit: 1024m
    image: "mdillon/postgis:9.6"
    expose:
      - 5432
